---
- name: my test playbook
  hosts: webservers
  become: true
  tasks:
    - name: add multiple users
      user: name='{{ item }}' state=present
      with_items:
        - dog
        - cat
        - rat
      
