---
- name: MY TEST PLAYBOOK
  hosts: webservers
  become: true
  tasks:
    - name: install httpd package
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"

    - name: start httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: installapache2 package
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: start apache2 service
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debain"

    - name: copy index.html
      copy:
        path: /home/ansadmin/index.html
        dest: /var/www/html
        mode: 0666


