---
- name: Murali Test playbook
  hosts: webservers
  become: true
  tasks:
    - name: service httpd stop
      service:
        name: httpd
        state: stopped
      notify: uninstall httpd
      ignore_errors: yes
        
  handlers:
    - name: uninstall httpd
      yum:
        name: httpd
        state: removed
        
