---

- name: install httpd package in RedHat
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == 'RedHat'
  notify: start httpd service

- name: install apache2 package in Debian
  yum:
    name: apache2
    state: present
  when: ansible_os_family == 'Debian'
  notify: start apache2 service

- name: copy file
  copy:
    src: /home/ansadmin/index.html
    dest: /var/www/html
    mode: 0666


